"""
Retrieval agent for the AEC pipeline.

The retrieval agent is responsible for providing a set of exemplar
sentences that illustrate how the target event might be realised in
natural language.  In the original AEC framework these exemplars are
generated by prompting a large language model with an event
definition.  In this implementation we support two simple strategies:

1. ``example_db`` – a user‑supplied mapping from event type names
   to lists of exemplar sentences.  When present the agent selects
   examples from this dictionary.
2. ``fallback`` – if no user examples are available the agent returns
   a synthetic exemplar generated from the schema itself.  The
   synthetic exemplar takes the form of a plain English prompt
   describing the event type and its roles.

The returned exemplars are intended to help the planning agent
disambiguate triggers and understand what kind of information to
extract for each role.  They are not used directly in scoring.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from .event_schema import EventSchema


@dataclass
class RetrievalAgent:
    """A simple retrieval agent.

    Parameters
    ----------
    example_db : Dict[str, List[str]], optional
        A mapping from event type names to lists of exemplar
        sentences.  If provided and a key matching the event type
        exists, the agent will draw examples from this dictionary.
    """

    example_db: Optional[Dict[str, List[str]]] = None

    def retrieve(self, schema: EventSchema, k: int = 3) -> List[str]:
        """Return up to ``k`` exemplar sentences for the given schema.

        If an ``example_db`` was provided and contains entries for
        ``schema.event_type`` then those examples are returned (up to
        ``k`` items).  Otherwise a synthetic exemplar describing the
        event is generated.
        """
        if self.example_db and schema.event_type in self.example_db:
            examples = self.example_db[schema.event_type][:k]
            return examples
        # fallback: generate a synthetic exemplar based on the roles
        role_desc = ", ".join(f"{role} ({typ.__name__})" for role, typ in schema.roles.items())
        synthetic = (
            f"An instance of the '{schema.event_type}' event is characterised by the trigger word(s) "
            f"and includes the following arguments: {role_desc}.\n"
            f"Provide a sentence that clearly mentions the trigger and all arguments."
        )
        return [synthetic]

    def retrieve_with_llm(
        self,
        schema_definition: str,
        k: int = 3,
        model: str = "gpt-4o",
    ) -> str:
        """Generate *k* exemplar sentences using an LLM (paper §3.1 Retrieval Agent).

        The LLM is prompted with the Python dataclass definition of the event
        schema and asked to produce fluent sentences that each contain a clear
        trigger word and as many populated argument roles as possible.  These
        sentences are used by the Planning Agent to ground its trigger
        hypotheses in concrete natural language examples.

        Parameters
        ----------
        schema_definition : str
            The Python dataclass definition of the target event type (as
            returned by :meth:`~AEC.ontology.OntologyManager.build_definitions`
            for a single event type).
        k : int, optional
            Number of exemplar sentences to generate.  Paper default: 3.
        model : str, optional
            LLM to use.  Defaults to ``"gpt-4o"``.

        Returns
        -------
        str
            A newline-separated string of *k* exemplar sentences, ready to be
            appended to a planning prompt as context.
        """
        from .llm_utils import call_llm  # local import

        system_prompt = "You are a helpful example generator for event extraction."
        user_prompt = (
            f"Given the following event type definition:\n\n"
            f"{schema_definition}\n\n"
            f"Generate {k} fluent English sentences. Each sentence must:\n"
            f"1. Contain a clear trigger word or phrase that evokes the event type.\n"
            f"2. Include textual mentions of as many argument roles as possible.\n"
            f"3. Be realistic and varied (different triggers, different contexts).\n\n"
            f"Output exactly one sentence per line, with no numbering or extra commentary."
        )
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        return call_llm(messages, model=model)